#!/usr/bin/env bash
#
# 3.Running_gkmsvm_train.sh
# Train gkm-SVM models on peak vs GC-matched null sequences
# using chromosome-based cross-validation and full-model fitting.
#
# Part of the RegulSNP-SVM pipeline.

set -euo pipefail

############################################
# User-configurable paths & parameters
############################################

# Path to gkmtrain binary (from lsgkm / gkm-SVM).
# You can either:
#   1) put gkmtrain in your $PATH, or
#   2) export GKMTRAIN_BIN=/path/to/gkmtrain before running.
GKMTRAIN_BIN="${GKMTRAIN_BIN:-gkmtrain}"

# Directory with FASTA files generated by:
#   1.From_gen_snp_seqs-*.r
#   1.From_gen_null_seqs-*.r
# Structure assumed:
#   ${FASTA_DIR}/training_fastas/<model>.train_chr<CHR>.fa
#   ${FASTA_DIR}/training_fastas/<model>.null.train_chr<CHR>.fa
FASTA_DIR="${FASTA_DIR:-./fastas_1000bp}"

# Output directories for cross-validation models and full models
MODEL_DIR="${MODEL_DIR:-./models/fit_models_1000bp}"
FULL_MODEL_DIR="${FULL_MODEL_DIR:-./models/full_models_1000bp}"

mkdir -p "${MODEL_DIR}" "${FULL_MODEL_DIR}"

# gkm-SVM hyper-parameters
lval=11   # word length
kval=7    # informative columns
dval=3    # mismatches
cval=1    # soft margin C
gval=1    # decay factor
tval=2    # kernel type (per lsgkm docs)
Mval=20000  # maximum number of support vectors (example)
Hval=1      # class weighting / other hyperparam (example)
eval=1      # evaluation flag (example, used in filename only)

############################################
# Models (cell types / peak sets)
############################################
# 这里按你上游脚本的命名来写一个默认列表，你也可以按需改：
models=(
  "CD8_eff_Post"
  "CD8_ex_Post"
  "CD8_mem_Pre"
  "CD8_mem_Post"
  "Naive_Pre"
  "Naive_Post"
  "Tfh_Pre"
  "Tfh_Post"
  "Th17_Pre"
  "Th17_Post"
  "Tregs_Pre"
  "Tregs_Post"
)

############################################
# Chromosome folds (10-fold CV by chr)
############################################

# All chromosomes included in training
all_chrs=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y)

# Define 10 folds, each a list of test chromosomes
fold0=(1 11)
fold1=(2 12)
fold2=(3 13)
fold3=(4 14)
fold4=(5 15)
fold5=(6 16)
fold6=(7 17)
fold7=(8 18)
fold8=(9 19)
fold9=(10 20 21 22 X Y)

all_folds=(0 1 2 3 4 5 6 7 8 9)

############################################
# Helper: join array with separator
############################################
join_by() {
  local IFS="$1"
  shift
  echo "$*"
}

############################################
# Main loop: per model, per fold
############################################

fasta_dir="${FASTA_DIR}"
train_dir="${fasta_dir}/training_fastas"

for model in "${models[@]}"; do
  echo "==============================="
  echo "Processing model: ${model}"
  echo "==============================="

  # Prefix for positive (true peaks) and negative (null) FASTA files
  true_prefix="${train_dir}/${model}.train_chr"
  null_prefix="${train_dir}/${model}.null.train_chr"

  ##############################
  # Cross-validation models
  ##############################
  for fold in "${all_folds[@]}"; do
    fold_var="fold${fold}"
    # shellcheck disable=SC2086
    test_chr_list=( ${fold_var} ) || true

    # Parse the fold variable (array by name)
    # We rely on the fact that fold0..fold9 are defined as arrays.
    # Use indirect expansion to get the actual array.
    # shellcheck disable=SC1083,SC2163,SC2178
    eval "fold_chrs=(\"\${${fold_var}[@]}\")"

    echo "  Fold ${fold}: test chromosomes = $(join_by "," "${fold_chrs[@]}")"

    # Train on all chromosomes except those in the test set
    train_chrs=()
    for chr in "${all_chrs[@]}"; do
      skip=false
      for tchr in "${fold_chrs[@]}"; do
        if [[ "${chr}" == "${tchr}" ]]; then
          skip=true
          break
        fi
      done
      if [[ "${skip}" == false ]]; then
        train_chrs+=("${chr}")
      fi
    done

    echo "    Train chromosomes = $(join_by "," "${train_chrs[@]}")"

    # Build list of FASTA files for training
    true_seq_files=()
    null_seq_files=()
    for chr in "${train_chrs[@]}"; do
      true_seq_files+=("${true_prefix}${chr}.fa")
      null_seq_files+=("${null_prefix}${chr}.fa")
    done

    # Check that all required files exist
    for f in "${true_seq_files[@]}" "${null_seq_files[@]}"; do
      if [[ ! -f "${f}" ]]; then
        echo "    [WARN] Missing FASTA file: ${f} (skipping fold ${fold} for model ${model})"
        continue 2
      fi
    done

    outpre="${MODEL_DIR}/${model}.n_fold${fold}.y${eval}.l${lval}.k${kval}.d${dval}.c${cval}.M${Mval}.H${Hval}"
    resultfile="${outpre}.model.txt"

    if [[ -f "${resultfile}" ]]; then
      echo "    [SKIP] ${resultfile} already exists."
      continue
    fi

    echo "    [RUN] Training CV model: ${outpre}"

    pos_tmp="${outpre}.pos.fa"
    neg_tmp="${outpre}.neg.fa"

    # Concatenate training FASTAs
    cat "${true_seq_files[@]}" > "${pos_tmp}"
    cat "${null_seq_files[@]}" > "${neg_tmp}"

    # Run gkmtrain
    "${GKMTRAIN_BIN}" \
      -l "${lval}" \
      -k "${kval}" \
      -d "${dval}" \
      -c "${cval}" \
      -g "${gval}" \
      -t "${tval}" \
      -M "${Mval}" \
      -H "${Hval}" \
      "${pos_tmp}" \
      "${neg_tmp}" \
      "${outpre}"

    # Optionally remove temporary concatenated FASTAs to save space
    rm -f "${pos_tmp}" "${neg_tmp}"

  done

  ##############################
  # Full model (all chromosomes)
  ##############################
  echo "  Training full model for ${model} (all chromosomes)"

  full_outpre="${FULL_MODEL_DIR}/${model}.y${eval}.l${lval}.k${kval}.d${dval}.c${cval}.M${Mval}.H${Hval}"
  full_resultfile="${full_outpre}.model.txt"

  if [[ -f "${full_resultfile}" ]]; then
    echo "  [SKIP] ${full_resultfile} already exists."
    continue
  fi

  full_true_seq_files=()
  full_null_seq_files=()
  for chr in "${all_chrs[@]}"; do
    full_true_seq_files+=("${true_prefix}${chr}.fa")
    full_null_seq_files+=("${null_prefix}${chr}.fa")
  done

  for f in "${full_true_seq_files[@]}" "${full_null_seq_files[@]}"; do
    if [[ ! -f "${f}" ]]; then
      echo "  [WARN] Missing FASTA file: ${f} (skipping full model for ${model})"
      continue 2
    fi
  done

  full_pos_tmp="${full_outpre}.pos.fa"
  full_neg_tmp="${full_outpre}.neg.fa"

  cat "${full_true_seq_files[@]}" > "${full_pos_tmp}"
  cat "${full_null_seq_files[@]}" > "${full_neg_tmp}"

  "${GKMTRAIN_BIN}" \
    -l "${lval}" \
    -k "${kval}" \
    -d "${dval}" \
    -c "${cval}" \
    -g "${gval}" \
    -t "${tval}" \
    -M "${Mval}" \
    -H "${Hval}" \
    "${full_pos_tmp}" \
    "${full_neg_tmp}" \
    "${full_outpre}"

  rm -f "${full_pos_tmp}" "${full_neg_tmp}"

done

echo "All gkm-SVM training completed."
